### ISSUE TITLE
Support pre-commit hooks

### ISSUE THREAD

**Issue by chriscunningham-qodea** [Cloud-Technology-Solutions/renovate-config#14]
Doesn't look like Renovate is suggesting hook bumps right now.

**Comment by sysadmiral** [comment]
pre-commit support is in beta: https://docs.renovatebot.com/modules/manager/pre-commit/

In general for work things I've avoided pre-stable versions of things. In this case perhaps we can relax that view but I'd be interested to know the consensus on this since...

**Comment by sysadmiral** [comment]
moving to https://github.com/Qodea/renovate-config
